name = "6-5610-project"
version = "0.1.0"

[[lean_exe]]
name = "main"
root = "Main"

[[lean_exe]]
name = "dependent"
root = "DependentMain"

[[lean_lib]]
name = "Cert"
roots = ["Cert", "CertCheck", "CertProofs", "CertTranslate", "Dependent", "Main"]

[[lean_exe]]
name = "cert"
root = "CertMain"

[[lean_exe]]
name = "cert-translate"
root = "CertTranslateMain"

[[lean_exe]]
name = "ping"
root = "PingTest"
